### ISSUE TITLE
Ability to cancel a running Monkey Script

### ISSUE THREAD

**Issue by iDigitalFlame** [skx/monkey#79]
Was trying to find a way to cancel a running Monkey script (in code directly, not command line based) and I don't see any method to do this properly.

Could there be a possibility of using a Context or something to stop execution in progress?
A change to the [Eval function](https://github.com/skx/monkey/blob/29357e427d852c5c8ef2c628796f35a77d4d3cf8/evaluator/evaluator.go#L30) like below would solve some of the issue (The function would bail after the current operation completes)

```
func Eval(x context.Context, node ast.Node, env *object.Environment) object.Object {
        switch node := node.(type) {
                select {
                        case <-x.Done():
                                return &object.Error{Message: x.Err().Error()}
                        default:
               }
        //Statements
```

Thanks

**Comment by skx** [comment]
An obvious issue now you've reported it!

I'd probably prefer to avoid changing the public interface, and would instead suggest adding add an `SetContext` method, with a default of `context.Background`.
