### ISSUE TITLE
Need help in adding Object Methods!

### ISSUE THREAD

**Issue by Jonak-Adipta-Kalita** [skx/monkey#87]
Hey there Buddy,
Can you pls tell me how you added Object Methods?

**Comment by skx** [comment]
Take a look at the pull-requests linked to #23, and #27.

**Comment by Jonak-Adipta-Kalita** [comment]
Alright, thanks!

**Comment by Jonak-Adipta-Kalita** [comment]
I found those repos but the thing why I still asked was coz if you have made any change after those prs?

**Comment by skx** [comment]
There have been other changes, but I don't recall when/where.

If you're curious I expect the best thing to do is to look at the git commit-log, or run "git blame" against the various files.

**Comment by Jonak-Adipta-Kalita** [comment]
alright thanks! have a great day, buddy!
