### ISSUE TITLE
execute env.mon got : identifier not found: self

### ISSUE THREAD

**Issue by wade-fs** [skx/monkey#89]
When I execute examples/env.mon:

_You are wade
Your home is /home/wade
Directories on your system PATH:
identifier not found: self
Error calling `string.split` : ERROR: identifier not found: self_

**Comment by skx** [comment]
That's a good find, thanks!

So we allow functions to be defined on types - when we write `function string.split` that means  that the function `split()` is available on variables of the type string.

So we can run this:

```
"steve kemp".split( " " )
```

And it looks like this example was written before I added this.  That means this code is wrong:

```
let paths = string.split( os.getenv("PATH"), ":" );
```

Instead it should be:

```
let paths = os.getenv("PATH").split(":");
```
